import { GoogleGenAI } from '@google/genai';

/**
 * @desc    Process AI Assistant Action (rephrase, change tone, summarize, generate full doc)
 * @route   POST /api/ai/process
 * @access  Private
 */
export const processAiAction = async (req, res) => {
  try {
    const { action, prompt, text, tone } = req.body;

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ message: 'Gemini API key is missing on the server.' });
    }

    const ai = new GoogleGenAI({ apiKey });

    let systemInstruction = '';
    let userPrompt = '';

    if (action === 'generate') {
      systemInstruction = 'You are an expert document author. Generate a well-structured, comprehensive document based on the user prompt using semantic HTML formatting (<p>, <h2>, <h3>, <ul>, <li>, <strong>, <em>, <table>). Do not include markdown code block syntax (like ```html), just output valid HTML.';
      userPrompt = `Create a complete document for: ${prompt}`;
    } else if (action === 'rephrase') {
      systemInstruction = 'You are a professional editor. Rephrase and improve the provided text for clarity, flow, and elegance. Keep the meaning intact. Output clean text or simple HTML if formatting exists.';
      userPrompt = `Rephrase this text: "${text}"`;
    } else if (action === 'tone') {
      systemInstruction = `You are a writing assistant. Adjust the tone of the provided text to be strictly ${tone || 'professional'}. Output clean text or simple HTML.`;
      userPrompt = `Change tone of this text to ${tone}: "${text}"`;
    } else if (action === 'summarize') {
      systemInstruction = 'You are an executive assistant. Provide a concise, bulleted HTML summary (using <ul> and <li> tags) of the provided text.';
      userPrompt = `Summarize this text: "${text}"`;
    } else {
      systemInstruction = 'You are an AI writing assistant. Assist the user with their document request.';
      userPrompt = prompt || text;
    }

    // Try gemini-2.5-flash, gemini-2.0-flash, or gemini-1.5-flash
    const candidateModels = ['gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-1.5-flash', 'gemini-flash'];
    let response = null;
    let lastErr = null;

    for (const modelName of candidateModels) {
      try {
        response = await ai.models.generateContent({
          model: modelName,
          contents: userPrompt,
          config: {
            systemInstruction
          }
        });
        if (response && response.text) break;
      } catch (err) {
        lastErr = err;
        console.warn(`[AI Controller] Model ${modelName} failed, trying next fallback...`);
      }
    }

    if (!response) {
      throw lastErr || new Error('No working Gemini model found.');
    }

    const resultText = response.text || '';

    // Clean any residual ```html code fence markdown if generated by model
    const cleanedResult = resultText
      .replace(/^```html\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/\s*```$/i, '')
      .trim();

    return res.json({ result: cleanedResult });
  } catch (error) {
    console.error('[AI Controller Error]:', error);
    return res.status(500).json({ message: error.message || 'Failed to process AI request' });
  }
};
